name = "bee2link-proxy"
main = "index.js"
compatibility_date = "2024-02-23"

[[d1_databases]]
binding = "DB"
database_name = "beezen-db"
database_id = "votre-id-ici" # L'utilisateur devra le remplir ou je lui demanderai
